USE ComicsCatalogue
GO

SELECT  tc.CONSTRAINT_NAME, tc.TABLE_SCHEMA, tc.TABLE_NAME, cu.COLUMN_NAME
	FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc 
		INNER JOIN(SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE) AS cu 
		ON tc.CONSTRAINT_NAME = cu.CONSTRAINT_NAME 
WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'