
select name, 
compatibility_level, 
collation_name, 
user_access_desc, 
is_read_only, 
is_auto_close_on, 
state_desc, 
is_auto_shrink_on, 
snapshot_isolation_state, 
is_read_committed_snapshot_on, 
recovery_model_desc, 
page_verify_option_desc, 
is_auto_create_stats_on, 
is_auto_update_stats_on,  
is_ansi_null_default_on, 
is_ansi_nulls_on, 
is_ansi_padding_on, 
is_arithabort_on, 
is_concat_null_yields_null_on, 
is_quoted_identifier_on, 
is_numeric_roundabort_on, 
is_recursive_triggers_on, 
is_cursor_close_on_commit_on, 
is_date_correlation_on,
is_db_chaining_on,
is_trustworthy_on,
is_parameterization_forced
from sys.databases
